const express = require("express");
const Patient = require("../models/patient");
const { authenticate } = require("../middleware/authenticate");
const router = express.Router();

router.use(authenticate);
router.post("/", async (req, res, next) => { try { if (req.user.role !== "user" && req.user.role !== "patient") return res.status(403).json({ message: "Only user accounts can become patients" }); const exists = await Patient.findOne({ userId: req.user._id }); if (exists) return res.status(409).json({ message: "Patient profile already exists for this user" }); const fields = ["dateOfBirth", "gender", "bloodGroup", "height", "weight", "medicalConditions", "allergies", "medications", "emergencyContacts", "insurance", "address", "medicalDocuments"]; const payload = Object.fromEntries(fields.filter((field) => req.body[field] !== undefined).map((field) => [field, req.body[field]])); const patient = await Patient.create({ userId: req.user._id, ...payload }); req.user.role = "patient"; req.user.profileCompleted = true; await req.user.save(); res.status(201).json({ message: "Patient profile created", patient }); } catch (error) { next(error); } });
router.get("/me", async (req, res, next) => { try { const patient = await Patient.findOne({ userId: req.user._id }); if (!patient) return res.status(404).json({ message: "Patient profile not found" }); res.json(patient); } catch (error) { next(error); } });
router.patch("/me", async (req, res, next) => { try { const fields = ["dateOfBirth", "gender", "bloodGroup", "height", "weight", "medicalConditions", "allergies", "medications", "emergencyContacts", "insurance", "address", "medicalDocuments"]; const updates = Object.fromEntries(fields.filter((field) => req.body[field] !== undefined).map((field) => [field, req.body[field]])); const patient = await Patient.findOneAndUpdate({ userId: req.user._id }, updates, { new: true, runValidators: true }); if (!patient) return res.status(404).json({ message: "Patient profile not found" }); res.json({ message: "Patient profile updated", patient }); } catch (error) { next(error); } });
module.exports = router;
