const mongoose = require("mongoose");
const ChatRoom = require("../models/chatroom");
const Message = require("../models/massage");

const access = (room, req) => req.user.role === "admin" || (req.patient && room.patientId.equals(req.patient._id)) || (req.caregiver && room.caregiverId.equals(req.caregiver._id));
exports.listRooms = async (req, res, next) => { try { const filter = req.user.role === "admin" ? {} : req.patient ? { patientId: req.patient._id } : req.caregiver ? { caregiverId: req.caregiver._id } : { _id: null }; const rooms = await ChatRoom.find(filter).populate("bookingId", "status serviceId").populate({ path: "lastMessageId", select: "message createdAt sender isSeen" }).sort({ updatedAt: -1 }); res.json({ rooms }); } catch (error) { next(error); } };
exports.getRoom = async (req, res, next) => { try { const room = await ChatRoom.findById(req.params.chatRoomId).populate("bookingId").populate("lastMessageId"); if (!room) return res.status(404).json({ message: "Chat room not found" }); if (!access(room, req)) return res.status(403).json({ message: "Unauthorized" }); res.json({ room }); } catch (error) { next(error); } };
exports.sendMessage = async (req, res, next) => { try { const room = await ChatRoom.findById(req.params.chatRoomId); if (!room) return res.status(404).json({ message: "Chat room not found" }); if (!access(room, req) || req.user.role === "admin") return res.status(403).json({ message: "Unauthorized" }); const text = req.body.message?.trim(); const attachments = Array.isArray(req.body.attachments) ? req.body.attachments : []; if (!text && !attachments.length) return res.status(400).json({ message: "A message or attachment is required" }); const senderRole = req.patient ? "patient" : "caregiver"; const entry = await Message.create({ chatRoomId: room._id, sender: { role: senderRole }, receiver: { role: senderRole === "patient" ? "caregiver" : "patient" }, message: text || "", attachments }); room.lastMessageId = entry._id; await room.save(); res.status(201).json({ message: "Message sent successfully", data: entry }); } catch (error) { next(error); } };
exports.listMessages = async (req, res, next) => { try { const room = await ChatRoom.findById(req.params.chatRoomId); if (!room) return res.status(404).json({ message: "Chat room not found" }); if (!access(room, req)) return res.status(403).json({ message: "Unauthorized" }); const limit = Math.min(Math.max(Number(req.query.limit) || 30, 1), 100); const before = req.query.before && mongoose.Types.ObjectId.isValid(req.query.before) ? req.query.before : null; const filter = { chatRoomId: room._id }; if (before) filter._id = { $lt: before }; if (req.user.role !== "admin") await Message.updateMany({ chatRoomId: room._id, "receiver.role": req.patient ? "patient" : "caregiver", isSeen: false }, { $set: { isSeen: true, seenAt: new Date() } }); const messages = await Message.find(filter).sort({ createdAt: -1 }).limit(limit).lean(); res.json({ chatRoomId: room._id, messages: messages.reverse() }); } catch (error) { next(error); } };
